OSSM-4491 Add missing configuration options to EnvoyExtAuthzHttp
Maistra/istio-operator pull request #1292
Opened 2023-09-01 15:31 UTC by mayleighnmyers

https://issues.redhat.com/browse/OSSM-4491

2023-09-05 14:50 UTC, jewertow requested changes

2023-09-05 14:50 UTC, jewertow commented on pkg/apis/maistra/conversion/extension_providers.go
> +				values["headersToUpstreamOnDeny"] = stringToInterfaceArray(config.HeadersToDownstreamOnDeny)
```suggestion
				values["headersToDownstreamOnDeny"] = stringToInterfaceArray(config.HeadersToDownstreamOnDeny)
```

2023-09-08 14:13 UTC, luksa approved these changes

2023-09-08 16:44 UTC, jewertow approved these changes

2023-09-08 16:47 UTC, merged