OSSM-5921: create istio-reader service account and cluster role when multi-cluster and cluster-wide modes are enabled
Maistra/istio-operator pull request #1749
Opened 2024-03-28 12:58 UTC by DeanDoyle1502

Currently, Istio Operator removes istio-reader-clusterrole and the related role binding, so users who deploy multi-cluster can't grant proper privileges for a remote control plane.

Acceptance Criteria:
When a user deploys multi-cluster SMCP, Istio Operator creates:
1) ServiceAccount istio-reader-service-account.
2) ClusterRole istio-reader-clusterrole-<smcp-name>.
3) ClusterRoleBinding istio-reader-clusterrole-<smcp-name>.

[https://issues.redhat.com/browse/OSSM-5921](url)

2024-03-28 12:59 UTC, luksa commented
/ok-to-test

2024-05-15 15:15 UTC, yxun commented
/test operator-lint-2-5

2024-05-15 17:32 UTC, jewertow commented on pkg/controller/versions/strategy_v2_5.go
> +	// Add in path to MultiCluster/gen-istio (location of directory???)
You don't have to add any other directory to chart mappings, because you added new templates to `istio-control/istio-discovery` that already exists here.
```suggestion
```

2024-05-15 17:35 UTC, yxun commented
There are string git errors in running the jobs of this PR. Not clear why only this PR has those git submodule commands

```
"git submodule update --init --recursive","component":"clonerefs","error"
```

2024-05-16 09:45 UTC, DeanDoyle1502 commented on pkg/controller/versions/strategy_v2_5.go
> +	// Add in path to MultiCluster/gen-istio (location of directory???)
Left in from previous plan to solve issue, I'll remove the comment

2024-05-16 10:42 UTC, eoinfennessy commented
/test

2024-05-16 10:43 UTC, eoinfennessy commented
/test all

2024-05-16 12:11 UTC, yxun commented
/test operator-unit-2-5

2024-05-16 19:01 UTC, yxun approved these changes

2024-05-22 13:07 UTC, jewertow requested changes

2024-05-22 13:07 UTC, jewertow commented on build/patch-charts.sh
> + # rm "${HELM_DIR}/istio-control/istio-discovery/templates/reader-clusterrolebinding.yaml"
Please just remove this code.

2024-05-22 13:07 UTC, jewertow commented on resources/helm/overlays/istio-control/istio-discovery/templates/reader-serviceaccount.yaml
> +{{- if .Values.global.clusterWide }}
This service account should be applied only when cluster-wide and moulti-cluster modes are enabled.

2024-05-22 13:07 UTC, jewertow commented on resources/helm/overlays/istio-control/istio-discovery/templates/reader-serviceaccount.yaml
> +{{- if .Values.global.clusterWide }}
You also forgot about closing this if statement.

2024-05-22 13:07 UTC, jewertow commented on resources/helm/v2.5/istio-control/istio-discovery/templates/reader-clusterrole.yaml
This cluster role and the related role binding should be applied conditionally when cluster-wide and multi-cluster modes are enabled.

2024-05-23 12:22 UTC, DeanDoyle1502 commented
This is still not correct conditional statement is giving inconsistent results

2024-06-04 11:04 UTC, DeanDoyle1502 commented
/ test all

2024-06-04 11:04 UTC, DeanDoyle1502 commented
/test all

2024-06-04 11:09 UTC, eoinfennessy approved these changes

2024-06-05 08:23 UTC, jewertow approved these changes

2024-06-05 08:30 UTC, merged