Update protobuf descriptors for generated 3scale API
Maistra/istio-operator pull request #188
Opened 2019-08-07 14:33 UTC by PhilipGough

For context, see https://github.com/3scale/3scale-istio-adapter/pull/111

2019-08-07 14:53 UTC, brian-avery commented on helm/maistra-threescale/values.yaml
> +tag: v1.0.0
Technically this should be updated in patch-charts.sh, but #176 is changing this.

2019-08-07 16:33 UTC, knrc requested changes
We will merge this separately from #176, however we need a maistra issue to cover this work and the version change moved to the patch scripts.

2019-08-07 18:15 UTC, PhilipGough commented
@knrc https://issues.jboss.org/browse/MAISTRA-653 covers it I think

2019-08-07 18:32 UTC, knrc commented
@PhilipGough Thanks, that does indeed cover it.  Can we have the PR updated to include the update for the patch scripts?

2019-08-08 08:31 UTC, PhilipGough commented
@knrc I've updated the version in the patch scripts as requested. However I'm not sure that value is not redundant now also. I've rebased on top of #176 and now the tags appear to be hardcoded in https://github.com/Maistra/istio-operator/blob/maistra-1.0/deploy/smcp-templates/servicemesh#L41 and https://github.com/Maistra/istio-operator/blob/maistra-1.0/deploy/smcp-templates/maistra#L43

Wondering if I can just remove the two tag references in this PR entirely at this point?

2019-08-08 13:31 UTC, knrc commented
@PhilipGough #716 wasn't merged when I made the comment and it was still under discussion, it looks as if it was merged yesterday afternoon.  Brian has indeed moved the versions to the new profile mechanism.

2019-08-12 15:10 UTC, knrc approved these changes

2019-08-12 15:11 UTC, brian-avery approved these changes

2019-08-12 15:13 UTC, merged