MAISTRA-1213 Deploy prometheus using global hub and tag (fixed sed pa…
Maistra/istio-operator pull request #351
Opened 2020-02-25 12:39 UTC by dgn

…ttern)

2020-02-25 14:52 UTC, luksa approved these changes

2020-02-25 14:55 UTC, luksa requested changes
I take back my approval. There are two containers in the deployment.yaml file. Don't we need to change the image in both?

2020-02-25 14:59 UTC, dgn commented
> I take back my approval. There are two containers in the deployment.yaml file. Don't we need to change the image in both?

Only after running the script there are two. The first one is injected using the sed command above the line I am touching.

2020-02-25 15:09 UTC, luksa approved these changes
Oh, sorry, my mistake. I tried this by manually modifying the yaml, but I modified the wrong container. Oops.

2020-02-26 22:27 UTC, rcernich approved these changes

2020-02-27 09:31 UTC, merged