MAISTRA-1878 Align ServiceMeshExtension CRD with maistra/istio
Maistra/istio-operator pull request #571
Opened 2020-10-01 16:17 UTC by dgn

Mostly, there was a rogue/outdated YAML in the manifest directory that broke the OLM bundle. While at it, I aligned the types.go with what we have in maistra/istio

2020-10-01 17:03 UTC, jwendell approved these changes

2020-10-01 17:36 UTC, brian-avery commented on deploy/maistra-operator.yaml
> +        olm.relatedImage.v2_0.3scale-istio-adapter: quay.io/3scale/3scale-istio-adapter:v1.0.0
Shouldn't this be 2.0? I think 3scale is shipping 2.0 with maistra 2.0.

2020-10-01 17:49 UTC, brian-avery commented on deploy/servicemesh-operator.yaml
> +        olm.relatedImage.v2_0.3scale-istio-adapter: registry.redhat.io/openshift-service-mesh/3scale-istio-adapter-rhel8:1.0.0
Same here

2020-10-01 18:20 UTC, brian-avery requested changes
I think we should avoid changing the 3scale version. Other than that, looks good.

2020-10-02 08:35 UTC, dgn commented
> I think we should avoid changing the 3scale version. Other than that, looks good.

See https://github.com/maistra/istio-operator/pull/573

2020-10-02 15:07 UTC, rcernich commented
Do we want this installed as part of the operator, or should it be installed with the other Istio CRDs?

2020-10-02 15:13 UTC, dgn commented
> Do we want this installed as part of the operator, or should it be installed with the other Istio CRDs?

Good point. I was thinking to install it with the operator because it's managed by us directly; it is consumed by the control planes though. Might make sense to include it with the Istio CRDs. wdyt?

2020-10-02 15:55 UTC, brian-avery approved these changes

2020-10-02 16:03 UTC, rcernich commented
Yeah, I think we should move it into `istio-init/files`, although I don't thing there's any harm, other than tying the install up with OLM, which could cause issues in the future if we remove it from the operator metadata.

2020-10-05 10:22 UTC, dgn commented
/retest

2020-10-05 10:23 UTC, dgn commented
I moved the CRD into the `istio-init` chart and split out CRD generation into its own script to accommodate that change. PTAL

2020-10-05 14:58 UTC, brian-avery approved these changes

2020-10-05 15:12 UTC, rcernich approved these changes

2020-10-05 15:32 UTC, merged